apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 15s
      httpMethod: POST

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: loki
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceID: false
        spanStartTimeShift: "-1m"
        spanEndTimeShift: "1m"
        customQuery: true
        query: '{job="rifa-app"} |~ "$${__trace.traceId}"'

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
        - name: TraceID
          datasourceUid: tempo
          matcherRegex: '"trace_id"\s*:\s*"([0-9a-fA-F]{16,32})"'
          url: "$${__value.raw}"
          urlDisplayLabel: Ver trace
        - name: TraceIDLogfmt
          datasourceUid: tempo
          matcherRegex: 'trace_id=([0-9a-fA-F]{16,32})'
          url: "$${__value.raw}"
          urlDisplayLabel: Ver trace
